import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import json
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GroupKFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve

# Directory and File Setup
BASE_DIR = Path(__file__).resolve().parent.parent
MASTER_CSV = BASE_DIR / "data" / "f1_lap_data_master.csv"
TRAINING_CSV = BASE_DIR / "data" / "f1_lap_data.csv"

# Model Features
MODEL_FEATURES = [
    "LapNumber",
    "is_lap_1",
    "endpoint_TyreLife",
    "Position",
    "endpoint_Stint",
    "LapTime_Seconds",
    "stint_comp",
]

# Hyperparameters & Threshold Definitions
PROBABILITY_THRESHOLD = 0.35  # Threshold for predicting a pit stop
CLASS_WEIGHTS = {0: 1, 1: 8}  # Rebalance 1:8 to prioritize pit recall
MAX_DEPTH = 5                 # Depth limit for trees
N_ESTIMATORS = 100            # Number of trees in Random Forest


def load_training_data():
    """
    Loads preprocessed feature CSVs generated by sample_test.py.
    """
    print(" [LOCAL PROCESSING] Loading processed datasets...")

    try:
        train_df = pd.read_csv(TRAINING_CSV)
        master_df = pd.read_csv(MASTER_CSV)

    except FileNotFoundError as e:
        print("\n [CRITICAL ERROR] Missing processed dataset.")
        raise FileNotFoundError("Run sample_test.py first.") from e

    print(" -> Training and master datasets loaded successfully.")

    X = train_df[MODEL_FEATURES].to_numpy()
    y = train_df["endpoint_shouldpit"].to_numpy()
    groups = train_df["race_group"].to_numpy()

    return (X, y, groups, MODEL_FEATURES, master_df)


def run_step_1_kfold(X, y, groups, feature_cols, n_splits=5):
    """
    Executes Group K-Fold Cross-Validation across distinct Grand Prix events.
    Trains a final Random Forest model on the full dataset once evaluation finishes.
    """
    print(f"\n [STEP 1] Running {n_splits}-Fold Group Cross-Validation with Random Forest...")
    print(f" -> Config: Threshold={PROBABILITY_THRESHOLD*100:.0f}% | Class Weights={CLASS_WEIGHTS} | Max Depth={MAX_DEPTH} | Estimators={N_ESTIMATORS}")

    gkf = GroupKFold(n_splits=n_splits)
    fold_accuracies, fold_precisions, fold_recalls, fold_f1s, fold_prauc = [], [], [], [], []
    
    oof_predictions = np.zeros(len(y))
    oof_probablities = np.zeros(len(y))

    for fold, (train_idx, val_idx) in enumerate(gkf.split(X, y, groups), 1):
        X_tr, y_tr = X[train_idx], y[train_idx]
        X_va, y_va = X[val_idx], y[val_idx]

        clf = RandomForestClassifier(
            n_estimators=N_ESTIMATORS,
            max_depth=MAX_DEPTH,
            min_samples_leaf=10,
            class_weight=CLASS_WEIGHTS,
            random_state=42,
            n_jobs=-1
        )
        clf.fit(X_tr, y_tr)
        
        # Apply custom probability threshold
        probs = clf.predict_proba(X_va)[:, 1]
        preds = (probs >= PROBABILITY_THRESHOLD).astype(int)

        oof_predictions[val_idx] = preds
        oof_probablities[val_idx] = probs

        acc = accuracy_score(y_va, preds)
        prec = precision_score(y_va, preds, pos_label=1, zero_division=0)
        rec = recall_score(y_va, preds, pos_label=1, zero_division=0)
        f1 = f1_score(y_va, preds, pos_label=1, zero_division=0)
        prauc = average_precision_score(y_va, probs)


        fold_accuracies.append(acc)
        fold_precisions.append(prec)
        fold_recalls.append(rec)
        fold_f1s.append(f1)
        fold_prauc.append(prauc)

        

        print(f" Fold {fold} | Acc: {acc*100:.2f}% | Pit Precision: {prec*100:.2f}% | Pit Recall: {rec*100:.2f}% | Pit F1: {f1:.2f}")

    print("\n" + "="*60)
    print(" K-FOLD CROSS-VALIDATION SUMMARY RESULTS (RANDOM FOREST)")
    print("="*60)
    print(f" Mean Overall Accuracy : {np.mean(fold_accuracies)*100:.2f}% (+/- {np.std(fold_accuracies)*100:.2f}%)")
    print(f" Mean Pit Precision    : {np.mean(fold_precisions)*100:.2f}%")
    print(f" Mean Pit Recall       : {np.mean(fold_recalls)*100:.2f}%")
    print(f" Mean Pit F1-Score     : {np.mean(fold_f1s):.2f}")
    print("="*60)

    #PRAUC calculations
    base_rate = y.mean()
    prauc_all = average_precision_score(y, oof_probablities)
    print(f" PR-AUC by chance      : {base_rate:.4f}")
    print(f" PR-AUC (out-of-fold)  : {prauc_all:.4f}")
    print(f" Lift over chance      : {prauc_all/base_rate:.2f}x")
    print(f" 'Never pit' baseline accuracy : {(1-base_rate)*100:.2f}%")


    print("\nOut-of-Fold Classification Report:")
    print(classification_report(y, oof_predictions, target_names=['Stay Out (0)', 'Pit Next Lap (1)']))

    # Save OOF Confusion Matrix Diagram
    plt.figure(figsize=(6, 5))
    cm = confusion_matrix(y, oof_predictions)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=['Stay Out', 'Pit Next Lap'], 
                yticklabels=['Stay Out', 'Pit Next Lap'])
    plt.title('Out-of-Fold Confusion Matrix (GroupKFold)')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.savefig(BASE_DIR / 'outputs' / 'confusion_matrix_kfold.png')
    plt.close()

    # Train final production Random Forest model on full dataset
    print("\n -> Training final production Random Forest model on full dataset...")
    final_clf = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        min_samples_leaf=10,
        class_weight=CLASS_WEIGHTS,
        random_state=42,
        n_jobs=-1
    )
    final_clf.fit(X, y)

    # Save model pkl file for Streamlit deployment
    joblib.dump(final_clf, BASE_DIR / "models" / "final_model.pkl")

    metrics = {
        "model_type": type(final_clf).__name__,
        "threshold": PROBABILITY_THRESHOLD,
        "pr_auc": float(average_precision_score(y, oof_probablities)),
        "pr_auc_chance": float(y.mean()),
        "never_pit_accuracy": float(1 - y.mean()),
        "accuracy": float(np.mean(fold_accuracies)),
        "precision": float(np.mean(fold_precisions)),
        "recall": float(np.mean(fold_recalls)),
        "f1": float(np.mean(fold_f1s)),
    }
    with open(BASE_DIR / "outputs" / "model_metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    # Save Feature Importance Diagram (Replaces plot_tree for Random Forests)
    plt.figure(figsize=(10, 5))
    importances = final_clf.feature_importances_
    indices = np.argsort(importances)

    plt.title('Random Forest Feature Importance')
    plt.barh(range(len(indices)), importances[indices], align='center')
    plt.yticks(range(len(indices)), [feature_cols[i] for i in indices])
    plt.xlabel('Relative Importance')
    plt.tight_layout()
    plt.savefig(BASE_DIR / 'outputs' / 'feature_importance.png', dpi=300)
    plt.close()

    print(" -> Saved 'final_model.pkl', 'confusion_matrix_kfold.png', and 'feature_importance.png'.")
    return final_clf


def demonstrate_race_predictions(clf, df, feature_cols, target_race_name="Abu Dhabi Grand Prix", target_year=2024):
    """
    Evaluates model performance on a single target race and interactively queries driver telemetry.
    """
    print("\n" + "="*70)
    print(f"      RACE DEMONSTRATION: {target_year} {target_race_name}      ")
    print("="*70)

    race_mask = (df['raceName'] == target_race_name) & (df['year'] == target_year)
    race_df = df[race_mask].copy()

    if race_df.empty:
        last_event = df[['year', 'raceName']].drop_duplicates().iloc[-1]
        target_year, target_race_name = last_event['year'], last_event['raceName']
        race_mask = (df['raceName'] == target_race_name) & (df['year'] == target_year)
        race_df = df[race_mask].copy()
        print(f" [INFO] Target race not found. Falling back to: {target_year} {target_race_name}")

    X_race = race_df[feature_cols].to_numpy()
    
    # Calculate probabilities and apply custom threshold
    probs = clf.predict_proba(X_race)[:, 1]
    race_df['Predicted_Pit'] = (probs >= PROBABILITY_THRESHOLD).astype(int)

    race_df['Actual_Status'] = race_df['endpoint_shouldpit'].map({1: 'PIT NEXT LAP', 0: 'Stay Out'})
    race_df['Predicted_Status'] = race_df['Predicted_Pit'].map({1: 'PIT NEXT LAP', 0: 'Stay Out'})

    def get_match_label(row):
        if row['endpoint_shouldpit'] == 1 and row['Predicted_Pit'] == 1:
            return "MATCH (Correct Pit Call)"
        elif row['endpoint_shouldpit'] == 0 and row['Predicted_Pit'] == 1:
            return "FALSE ALARM (Early Call)"
        elif row['endpoint_shouldpit'] == 1 and row['Predicted_Pit'] == 0:
            return "MISSED PIT STOP"
        return "MATCH (Stay Out)"

    race_df['Evaluation'] = race_df.apply(get_match_label, axis=1)

    display_cols = [
        'driverCode', 'LapNumber', 'is_lap_1', 'endpoint_Stint', 'endpoint_TyreLife', 
        'stint_comp', 'LapTime_Seconds', 'Actual_Status', 'Predicted_Status', 'Evaluation'
    ]

    race_accuracy = (race_df['endpoint_shouldpit'] == race_df['Predicted_Pit']).mean() * 100
    actual_pits = race_df['endpoint_shouldpit'].sum()
    caught_pits = len(race_df[(race_df['endpoint_shouldpit'] == 1) & (race_df['Predicted_Pit'] == 1)])
    
    print("-" * 70)
    print(f" Race Performance Summary for {target_year} {target_race_name}:")
    print(f" - Overall Race Match Accuracy: {race_accuracy:.2f}%")
    print(f" - Pit Stops Caught: {caught_pits} / {actual_pits} actual pit stops")
    print("-" * 70)

    output_filename = BASE_DIR / f"race_demo_{target_year}_{target_race_name.replace(' ', '_')}.csv"
    race_df[display_cols].to_csv(output_filename, index=False)
    print(f" -> Exported full race breakdown to '{output_filename}'\n")

    available_drivers = sorted(race_df['driverCode'].dropna().unique().tolist())
    print(f"Available Drivers in this race: {', '.join(available_drivers)}")

    while True:
        user_input = input("\nEnter a Driver Code (e.g., VER, HAM, LEC) or type 'exit' to quit: ").strip().upper()

        if user_input in ['EXIT', 'QUIT', 'Q', '']:
            print("\nExiting demonstration inspection. Done!")
            break

        driver_df = race_df[race_df['driverCode'] == user_input]

        if driver_df.empty:
            matching_rows = race_df[race_df['driverCode'].str.contains(user_input, case=False, na=False)]
            if not matching_rows.empty:
                driver_df = matching_rows
                user_input = driver_df['driverCode'].iloc[0]
            else:
                print(f" [!] Driver '{user_input}' not found in this race. Choose from: {', '.join(available_drivers)}")
                continue

        driver_pit_laps = driver_df[display_cols].sort_values(by='LapNumber')

        print(f"\n" + "="*70)
        print(f" TELEMETRY & PREDICTIONS FOR DRIVER: {user_input}")
        print("="*70)

        if driver_pit_laps.empty:
            print(f"No telemetry records found for driver {user_input}.")
        else:
            print(driver_pit_laps.to_string(index=False))

        driver_acc = (driver_df['endpoint_shouldpit'] == driver_df['Predicted_Pit']).mean() * 100
        driver_actual_pits = driver_df['endpoint_shouldpit'].sum()
        driver_caught_pits = len(driver_df[(driver_df['endpoint_shouldpit'] == 1) & (driver_df['Predicted_Pit'] == 1)])
        print("-" * 70)
        print(f" Driver Summary ({user_input}): Match Accuracy = {driver_acc:.2f}% | Pit Calls Caught = {driver_caught_pits}/{driver_actual_pits}")
        print("-" * 70)


if __name__ == "__main__":
    X, y, groups, feature_cols, full_df = load_training_data()
    clf = run_step_1_kfold(X, y, groups, feature_cols, n_splits=5)
    demonstrate_race_predictions(clf, full_df, feature_cols, target_race_name="Abu Dhabi Grand Prix", target_year=2024)